
clat_faqs = {
    "biggest law exams in india": "The biggest law exams in India for 5-year law programs are CLAT, AILET, SLAT, LSAT, and MH CET. Each exam is applicable to different colleges.",
    "top 5 law colleges in india": "The top 5 law colleges in India are: 1) NLSIU Bangalore, 2) NLU Delhi, 3) NLU Hyderabad, 4) NUJS Kolkata, and 5) JMI New Delhi.",
    "age limit for lawyer": "There is no age bar for pursuing law as a career. For 5-year LLB, the age limit is 20 years (General) and 22 years (Reserved categories). 3-year LLB has no age limit.",
    "nri eligibility for clat": "NRIs who fulfill CLAT eligibility requirements can appear for the exam. The main criterion is scoring at least 45% marks in the qualifying exam.",
    "clat negative marking": "Yes, CLAT has negative marking. Each correct answer gives +1 mark, while each wrong answer deducts 0.25 marks.",
    "delhi nlu through clat": "No, NLU Delhi does not accept CLAT scores. They conduct their own AILET exam for admissions.",
    "clat cutoff for nlu": "Top 5 NLUs require 95-100 marks. Other NLUs have cutoffs around 80-85 marks.",
    "failed clat application": "If your CLAT application isn't submitted successfully, you'll need to fill it out again from the beginning.",
    "check clat registration status": "Log in with your credentials on the official website. Successful login means your application is submitted. You'll also receive a confirmation email.",
    "clat exam duration": "CLAT is a 2-hour exam with 120 multiple-choice questions.",
    "forgot clat password": "Click 'Forgot Password' on the login page, enter your registered mobile number, request OTP, and reset your password.",
    "clat counselling fee refund": "Yes, if you don't take admission to any NLU, you'll get a full refund of the counselling fee.",
    "sports quota in nlu": "GNLU Gandhinagar has 4 supernumerary seats under sports quota (2 for boys, 2 for girls).",
    "rough sheets in clat": "Yes, exam centers provide rough sheets for calculations and rough work.",
    "clat answer key release": "The final answer key is typically released 5-6 days after the exam.",
    "clat counselling fee": "₹30,000 for General category, ₹20,000 for SC/ST and reserved categories.",
    "clat application documents": "You need: 10th/12th mark sheets, ID proof, email, passport photos, signature, category certificate (if applicable), PWD/BPL certificates (if applicable).",
    "blank clat application": "A blank application form means your submission wasn't successful. You'll need to fill it out again.",
    "nlu campus visits": "Open campus visits are typically scheduled a month before the exam. Candidates get one visit per cycle.",
    "download clat admit card": "Visit consortiumofnlus.ac.in, login with credentials, and click 'Download CLAT Admit Card'.",
    "sectional cutoff in clat": "No, there is no sectional cutoff in CLAT.",
    "seats reserved for females": "30 seats are reserved for female candidates across NLUs (excluding NRI female candidates).",
    "80 marks in clat": "With 80 marks, General category candidates can get into NLUs except the top 5 and DNLU.",
    "specially-abled provisions": "Specially-abled candidates can choose their own scribe or request one from the CLAT office.",
    "is 90 a good clat score": "Yes, 90+ is considered a good CLAT score, though selection depends on percentile and rank.",
    "best city for clat coaching": "Delhi is considered the best city for CLAT coaching.",
    "hardest clat section": "Legal Reasoning is considered the hardest section in CLAT.",
    "best stream for clat": "The Arts stream is considered best for CLAT aspirants.",
    "clat vs jee/neet": "CLAT is considered easier than IIT JEE and NEET, but it's more trick-based.",
    "self-study for clat": "Yes, but difficult due to increasing competition. Coaching is recommended.",
    "newspaper for clat prep": "The Hindu is best. Also use notes from Knowledge Nation Law Centre's research team.",
    "12th marks importance": "No, but you need at least 45% in 12th to appear for CLAT.",
    "clat prep in 2 months": "Difficult but possible with proper coaching from Knowledge Nation Law Centre.",
    "study hours for clat": "3 hours daily for 12 months is sufficient to crack CLAT.",
    "colleges under clat": "25 NLUs across India (excluding Delhi NLU).",
    "best nlu for placements": "NLU Bengaluru and NLU Hyderabad have the best placement records.",
    "nlu delhi fees": "Approximately ₹15 lakhs for the 5-year program.",
    "best clat study material": "Knowledge Nation Law Centre provides the best study material.",
    "du for law": "Delhi University is considered one of the best colleges for Law.",
    "best du llb campus": "CLC (Campus Law Centre) is the best for LLB at DU.",
    "du llb difficulty": "Not easy - requires rigorous preparation. Coaching is recommended.",
    "du law colleges": "DU has 3 law colleges: CLC, LC1, and LC2.",
    "du llb seats": "Approximately 3000 seats across all DU law campuses.",
    "du llb placements": "Yes, DU has a separate placement cell for law students.",
    "du hostel for law": "Yes, DU provides hostel facilities for law students.",
    "du llb applicants": "About 50,000 students apply for DU LLB each year.",
    "clat english syllabus": "English includes comprehension passages, vocabulary, grammar, sentence correction, and inference-based questions.",
    "clat current affairs syllabus": "This section tests knowledge of current events, awards, sports, international affairs, and legal news.",
    "clat legal reasoning syllabus": "Legal passages based on facts and principles, with questions on legal maxims, legal GK, and reasoning.",
    "clat logical reasoning syllabus": "Includes short passages, conclusions, arguments, cause-effect, puzzles, arrangements, and assumptions.",
    "clat quantitative techniques syllabus": "Covers basic math: percentages, ratios, profit-loss, time-speed-distance, bar graphs, tables, etc.",
    "clat subject-wise weightage": "English: 20%, Current Affairs: 25%, Legal Reasoning: 25%, Logical Reasoning: 20%, Quantitative Techniques: 10%",
    "current affairs weightage": "Current Affairs & GK usually carry around 25% of the total questions, i.e., approx 30 out of 120.",
    "llb in jnu": "No, JNU doesn't offer LLB programs.",
    "direct du llb admission": "No, cracking DU LLB/CUET PG LAW exam is mandatory for DU's 3-year law program.",
    "good du llb score": "This depends on the exam's difficulty level each year.",
    "ailet vs clat difficulty": "AILET is more difficult as it has fewer seats compared to CLAT.",
    "clat syllabus": "The CLAT 2025 syllabus includes: English Language, Current Affairs including GK, Legal Reasoning, Logical Reasoning, and Quantitative Techniques.",
    "english section questions": "The English section contains around 22-26 questions based on comprehension passages and vocabulary.",
    "clat 2025 date": "CLAT 2025 is expected to be held on December 1, 2024.",
    "nlsiu bangalore cutoff": "The CLAT 2024 cutoff for NLSIU Bangalore was AIR 114 for General category.",
    "application process": "You can apply for CLAT 2025 via the official website consortiumofnlus.ac.in. Application typically opens in July and closes in November.",
    "eligibility": "Candidates must have passed Class 12 or equivalent with at least 45% marks (40% for reserved categories).",
    "age limit": "There is no upper age limit for appearing in CLAT.",
    "marking scheme": "Each correct answer is awarded 1 mark. 0.25 marks are deducted for every wrong answer.",
    "number of questions": "There are a total of 120 questions in CLAT 2025.",
    "duration": "CLAT is a 2-hour (120 minutes) test.",
    "legal reasoning questions": "Legal Reasoning section consists of 28–32 questions based on legal passages."
}
